package openapi

import (
	"fmt"

	"github.com/getkin/kin-openapi/openapi3"
)

// Load lê e valida um documento OpenAPI 3 (YAML ou JSON) do caminho informado,
// resolvendo as referências $ref. Retorna o documento pronto para descoberta.
func Load(path string) (*openapi3.T, error) {
	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true

	doc, err := loader.LoadFromFile(path)
	if err != nil {
		return nil, fmt.Errorf("loading spec %q: %w", path, err)
	}

	// DisableExamplesValidation tolerates specs generated by frameworks like
	// Spring Boot that emit string literals as examples for integer fields
	// (e.g. example: "0001" on type: integer). The mock behaviour is not
	// affected because examples are only used as hints, never enforced.
	if err := doc.Validate(loader.Context, openapi3.DisableExamplesValidation()); err != nil {
		return nil, fmt.Errorf("validating spec %q: %w", path, err)
	}

	return doc, nil
}
